# Generated by Django 5.1.4 on 2025-01-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Lugar',
                'db_table': 'lugar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('lugar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pruebamod3.lugar')),
                ('serves_hot_dogs', models.BooleanField(default=False)),
                ('serves_pizza', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'db_table': 'restaurante',
                'ordering': ['lugar'],
            },
        ),
        migrations.CreateModel(
            name='Camarero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebamod3.restaurante')),
            ],
            options={
                'verbose_name': 'Camarero',
                'db_table': 'camarero',
                'ordering': ['name'],
            },
        ),
    ]
