# Generated by Django 5.1.4 on 2025-01-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebamod1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebamod1.reportero')),
            ],
            options={
                'verbose_name': 'Articulo',
                'db_table': 'articulo',
                'ordering': ['headline'],
            },
        ),
    ]
