# Generated by Django 5.1.4 on 2025-01-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebamod2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['title'], 'verbose_name': 'Publicacion'},
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='publicacion',
        ),
    ]
