# Generated by Django 5.1.4 on 2025-01-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebamod2', '0002_alter_publicacion_options_alter_publicacion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['headline'], 'verbose_name': 'Noticia'},
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='noticia',
        ),
    ]
